git:
    user:
        name: ENC[AES256_GCM,data:FkupOPgFOlj5YGd0,iv:GTpd8Wf6uraRtjE3sDU1QJkARiBqf31Fv5gObkjRyRo=,tag:eGvWIjdnKxQLy+zswBBlHg==,type:str]
        email: ENC[AES256_GCM,data:oZxtqNjicrdFg2ERbDzFS7ez,iv:9LELVnZpYRVh6qcurMJsRA6tqWZx1esFY6nXehLJm/U=,tag:jWvtYcImFxSU34dxFQAqwg==,type:str]
sops:
    age:
        - recipient: age1sq90mkgkuvux2usxjw0j65pkf57w3jh85x8fgq548rtz2pyfdd9scmwxj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWlVKSlg5OEFBRGJ2N2ov
            ZmsyM0lEeTltQ3pTSElnckVjam1SVDNBY1ZNCkh0cEFkQmdDYlRhZ3h0YmJqZ2tG
            aDUvdmQrTmFOTGhvWTNvY1ozc3JPR0UKLS0tIFpCNDB4ajh2QUM2U3JQaVllbVlT
            YWhaYzBrV0t1MDM0NHhzT1ZESU1veU0KvpzsyyCltIZCUulbHAUYKGfXSxzLQin+
            L0zzWOf69QV8d463TAJpNJc8INS47XGW0jPdBKlmlbAcexHP5f3b9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T12:12:26Z"
    mac: ENC[AES256_GCM,data:6HCvtWgKvjWdIzKwMZkOQTr08hZ8je8JKSsoKOoI1jCneQts44Tz9F2HSKGV8Er4W8PUvP8bk+BNLme4xRQpMnFXI62MocwzI4LeNa3/Yp4/1BeMiyZ5mf6GziqMweLUuBOTq4S4yLIDcu3m68fHUadbuP+V2Ef/bNVF2+v98PQ=,iv:cSw0wwpFxnqyXDzibk0Z5bgYq7NHS6mLfRu4jPsnQXA=,tag:1hOYOeLJSZDZtW9YJXRM9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
